server.port: 8080

logging:
  level:
    org.springframework.web: error
    org.hibernate: error
    org.apache.http: error

spring:
  servlet:
   multipart:
     enabled: false
     max-file-size: 20MB
     max-request-size: 50MB
  messages.basename: validation
  thymeleaf.cache: false
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
        #type: trace
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
cloudinary:
  cloud_name: sgrkale
  api_key: 423365436679876
  api_secret: lc9l1fKrtifRCquCezCUSbGOLTQ


---
spring:
  profiles: mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/payment?verifyServerCertificate=false&useSSL=true"
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

---
spring:
  profiles: postgres
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
---
spring:
  profiles: errorlogs
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: false
  messages:
    basename: validation
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.web: error
    org.hibernate: error
    org.apache.http: error
management:
  endpoints:
    web:
      exposure:
        include: "*"